server:
  port: 8080

spring:
  application:
    name: APIGateway

  cloud:
    gateway:
      routes:
        - id: CUSTOMERSERVICE
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1

        - id: ADMINSERVICE
          uri: lb://ADMINSERVICE
          predicates:
            - Path=/admin/**
          
        - id: NOTIFICATIONSERVICE
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/notification/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/