server:
  port: 3002
spring:
  application:
    name: AdminService
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    password: project123
    url: jdbc:mysql://localhost:3306/customerloan
    username: project
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  file:
    name: logs/customer-service.log
  level:
    root: INFO